services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./volumes/mysql/data/:/var/lib/mysql
      - ./volumes/mysql/backups/:/backups
      # TODO: mount the mysql state as a volume

  zenml:
    image: zenmldocker/zenml-server
    ports:
      - "8080:8080"
    environment:
      ZENML_STORE_URL: mysql://root:password@mysql/zenml
      ZENML_STORE_BACKUP_DIRECTORY: /backups
      ZENML_STORE_BACKUP_STRATEGY: dump-file
      ZENML_SERVER_AUTO_ACTIVATE: 1
      ZENML_DEFAULT_USER_NAME: default
      ZENML_ENABLE_IMPLICIT_AUTH_METHODS: "true"
      AWS_PROFILE: zenml
      # ZENML_DEFAULT_USER_PASSWORD: The password to use for the initial admin user account. Defaults to an empty password value, if not set.
    volumes:
      - ~/.aws:/home/zenml/.aws
      - ./volumes/mysql/data/:/var/lib/mysql
    links:
      - mysql
    depends_on:
      - mysql
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: on-failure
