services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  # TODO: mount the mysql state as a volume
  zenml:
    image: zenmldocker/zenml-server
    ports:
      - "8080:8080"
    environment:
      - ZENML_STORE_URL=mysql://root:password@mysql/zenml
    links:
      - mysql
    depends_on:
      - mysql
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: on-failure
